// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCHSQ04bYx-TFKJV1NnYcY9LJArlXtjGIk',
    appId: '1:536869947873:web:ca40834cf5bedad2a3eaa0',
    messagingSenderId: '536869947873',
    projectId: 'scandr1',
    authDomain: 'scandr1.firebaseapp.com',
    storageBucket: 'scandr1.appspot.com',
    measurementId: 'G-FHVPD9Q7XC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBsKEnA1NFfU2ku0vatgSDTJpoRcAYgaVs',
    appId: '1:536869947873:android:c7aede0129c64e82a3eaa0',
    messagingSenderId: '536869947873',
    projectId: 'scandr1',
    storageBucket: 'scandr1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_g1aY3QohX4Qk1IrJkkd71-hXmHdbYss',
    appId: '1:536869947873:ios:2013e26e719bdda0a3eaa0',
    messagingSenderId: '536869947873',
    projectId: 'scandr1',
    storageBucket: 'scandr1.appspot.com',
    iosBundleId: 'com.example.scanDr1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCHSQ04bYx-TFKJV1NnYcY9LJArlXtjGIk',
    appId: '1:536869947873:web:4db3aec1bbe89654a3eaa0',
    messagingSenderId: '536869947873',
    projectId: 'scandr1',
    authDomain: 'scandr1.firebaseapp.com',
    storageBucket: 'scandr1.appspot.com',
    measurementId: 'G-DNDTBSDL69',
  );
}
